/** Render own source in about:blank. No URL navigation or browser network requests.
 * This is a DOM/UI test with mocked fetch, NOT an end-to-end platform test.
 * Required here because the build environment has an administrator URLBlocklist.
 */
import assert from 'node:assert/strict';import {mkdtempSync,rmSync,writeFileSync,mkdirSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {CDPBrowser} from '../src/adapters/cdp.mjs';import {Store} from '../src/core/store.mjs';import {Engine} from '../src/worker/engine.mjs';import {DemoAdapter} from '../src/adapters/demo.mjs';import {VERSION} from '../src/core/policy.mjs';
const dir=mkdtempSync(join(tmpdir(),'biedbot-dom-')),results=[];let browser,store;
async function check(name,fn){const start=Date.now();await fn();results.push({name,status:'passed',durationMs:Date.now()-start});console.log('PASS',name);}
try{
  store=new Store(':memory:');store.updateSettings({company:'Autobedrijf Voorbeeld',signoff:'Inkoopteam',autopilot:true,budget:1000000});let now=Date.now();const adapter=new DemoAdapter(store,{replyDelay:1,now:()=>now}),engine=new Engine(store,adapter,{now:()=>now});for(let i=0;i<150;i++){now+=100;await engine.tick();}store.updateSettings({autopilot:false});
  const snapshot={...store.dashboard(now),version:VERSION,csrf:'dom-fixture'};
  browser=await new CDPBrowser().launch({profileDir:join(dir,'browser'),fixtureTest:true});
  await browser.call('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false},browser.session);
  const tree=await browser.call('Page.getFrameTree',{},browser.session);const html=`<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${readFileSync('src/ui/style.css','utf8')}</style></head><body><div id="app"></div><div id="toast" role="status"></div></body></html>`;
  await browser.call('Page.setDocumentContent',{frameId:tree.frameTree.frame.id,html},browser.session);
  await browser.evaluate(`window.__errors=[];window.addEventListener('error',e=>__errors.push(e.message));window.addEventListener('unhandledrejection',e=>__errors.push(String(e.reason)));window.__fixture=${JSON.stringify(snapshot)};window.__calls=[];window.fetch=async(path,opts={})=>{const data=opts.body?JSON.parse(opts.body):{};__calls.push({path,data});if(path==='/api/settings')Object.assign(__fixture.settings,data);if(path==='/api/autopilot')__fixture.settings.autopilot=data.enabled;return new Response(JSON.stringify(path==='/api/state'?__fixture:{ok:true}),{status:200,headers:{'content-type':'application/json'}});};`);
  await browser.evaluate(`(()=>{${readFileSync('src/ui/app.js','utf8')}\n})()`);
  await check('Onboarding-DOM laadt in echte Chromium',async()=>{await browser.waitFor("!!document.querySelector('#onboarding')");assert.ok(await browser.evaluate("document.body.textContent.includes('Jij de auto')"));});
  await check('Onboarding-formulier heeft correcte API-velden',async()=>{await browser.evaluate(`(()=>{const f=document.querySelector('#onboarding');f.elements.company.value='Autobedrijf Voorbeeld';f.elements.signoff.value='Inkoopteam';f.elements.town.value='Delft';f.elements.understand.checked=true;f.requestSubmit();})()`);await browser.waitFor("!!document.querySelector('[data-action=toggle]')");assert.ok(await browser.evaluate("__calls.some(x=>x.path==='/api/settings'&&x.data.onboardingDone===true&&x.data.company==='Autobedrijf Voorbeeld')"));});
  await check('Autopilot-besturing doet API-aanroep zonder berichtgoedkeuring',async()=>{await browser.evaluate("document.querySelector('[data-action=toggle]').click()");await browser.waitFor("document.body.textContent.includes('DEMO ACTIEF')");assert.ok(await browser.evaluate("__calls.some(x=>x.path==='/api/autopilot'&&x.data.enabled===true)"));});
  mkdirSync('reports',{recursive:true});
  await check('Desktopdashboard zonder runtimefouten',async()=>{assert.deepEqual(await browser.evaluate('window.__errors'),[]);const png=await browser.call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false},browser.session);writeFileSync('reports/dashboard-desktop.png',Buffer.from(png.data,'base64'));});
  await check('Inbox toont berichten en hard plafond',async()=>{await browser.evaluate("document.querySelector('[data-page=inbox]').click()");await browser.waitFor("!!document.querySelector('.chat-money')");assert.ok(await browser.evaluate("document.body.textContent.includes('Hard plafond')"));const png=await browser.call('Page.captureScreenshot',{format:'png'},browser.session);writeFileSync('reports/gesprekken-desktop.png',Buffer.from(png.data,'base64'));});
  for(const page of ['scout','deals','settings','health','billing','today'])await check('Navigatie '+page,async()=>{await browser.evaluate(`document.querySelector('[data-page=${page}]').click()`);await browser.waitFor(`document.querySelector('[data-page=${page}]').getAttribute('aria-current')==='page'`);assert.ok(await browser.evaluate("document.querySelector('main').textContent.length>300"));});
  await check('Geen horizontale pagina-overflow op 390px',async()=>{await browser.call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},browser.session);await new Promise(r=>setTimeout(r,200));const sizes=await browser.evaluate('({full:document.documentElement.scrollWidth,view:window.innerWidth})');assert.ok(sizes.full<=sizes.view+1,JSON.stringify(sizes));const png=await browser.call('Page.captureScreenshot',{format:'png'},browser.session);writeFileSync('reports/dashboard-mobiel.png',Buffer.from(png.data,'base64'));});
  await check('Noodstop doet API-aanroep enabled false',async()=>{await browser.evaluate("document.querySelector('[data-action=stop]').click()");await browser.waitFor("document.body.textContent.includes('KLAAR VOOR START')");assert.ok(await browser.evaluate("__calls.some(x=>x.path==='/api/autopilot'&&x.data.enabled===false)"));});
  await check('Geen JavaScriptfouten na alle pagina’s',async()=>assert.deepEqual(await browser.evaluate('window.__errors'),[]));
}catch(e){results.push({name:'DOM_TEST_FAILURE',status:'failed',error:e.stack});console.error(e);process.exitCode=1;}
finally{await browser?.close();store?.close();rmSync(dir,{recursive:true,force:true});mkdirSync('reports',{recursive:true});writeFileSync('reports/browser-dom-tests.json',JSON.stringify({executedAt:new Date().toISOString(),platform:process.platform,node:process.version,scope:'Echte Chromium DOM/render-test met eigen broncode en gemockte fetch in about:blank; geen navigatie, geen Windows-/Marktplaats-end-to-endtest.',passed:results.filter(x=>x.status==='passed').length,failed:results.filter(x=>x.status==='failed').length,results},null,2));}
