const $=q=>document.querySelector(q);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null?'Onbekend':new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v);
const number=v=>new Intl.NumberFormat('nl-NL').format(v||0);
const clock=v=>new Date(v).toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'});
let state=null, csrf='', page='today', selected=null, search='', showAll=false, busy=false;
const icons={today:'M3 10 12 3l9 7v10H3z M9 20v-7h6v7',scout:'M20 20l-5-5 M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14',inbox:'M3 4h18v13H8l-5 4z M7 8h10 M7 12h7',deals:'m4 12 5 5L20 6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v4 M12 18v4 M2 12h4 M18 12h4 M5 5l3 3 M16 16l3 3 M5 19l3-3 M16 8l3-3',health:'M2 12h5l3-8 4 16 3-8h5',billing:'M3 5h18v14H3z M3 10h18 M6 15h4'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.today}" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const labels={NEW:'Gepland',WAITING_INFO:'Wacht op reactie',NEGOTIATING:'In onderhandeling',HOT_LEAD:'Hete lead',DECLINED:'Afgesloten',SUPPRESSED:'Niet meer benaderen',REVIEW:'Controle nodig',PURCHASED:'Gekocht',LOST:'Niet gekocht'};
const badgePhase=s=>`<span class="badge ${s==='HOT_LEAD'||s==='PURCHASED'?'green':s==='REVIEW'?'demo':''}">${esc(labels[s]||s)}</span>`;
const eventNames={SCOUT_FOUND:'Nieuwe kansen beoordeeld',CONTACT_RESERVED:'Nieuwe advertentie geselecteerd',SEND_ATTEMPT:'Bericht wordt verwerkt',SEND_CONFIRMED:'Demobericht bevestigd',HOT_LEAD:'Prijs voor bezichtiging afgesproken',AUTOPILOT_STARTED:'Autopilot geactiveerd',EMERGENCY_STOP:'Autopilot gepauzeerd',SILENT_STOP:'Gesprek automatisch gestopt',REVIEW:'Uitzondering apart gezet',SETTINGS_UPDATED:'Instellingen opgeslagen',DEMO_RESET:'Demonstratie opnieuw gestart',DELIVERY_UNCERTAIN:'Verzending onzeker',WORKER_PAUSED:'Worker gestopt'};
async function api(path,options={}){
  const r=await fetch(`/api/${path}`,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json','X-Biedbot-Csrf':csrf,...(options.headers||{})}});
  const data=await r.json();if(!r.ok)throw new Error(data.error||'Verzoek mislukt.');return data;
}
const post=(path,data={})=>api(path,{method:'POST',body:JSON.stringify(data)});
function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.className=error?'error':'';t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display='none',5000);}
async function refresh(force=false){
  try{state=await api('state');csrf=state.csrf;
    if(force||!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))render();
  }catch(e){if(force)toast(e.message,true);}
}
const button=(label,action,style='',extra='')=>`<button class="button ${style}" data-action="${action}" ${extra}>${label}</button>`;
const heading=(eye,title,sub,actions='')=>`<div class="heading"><div><div class="eyebrow">${eye}</div><h1>${title}</h1><p class="sub">${sub}</p></div><div class="buttons">${actions}</div></div>`;
function layout(content){
  const s=state.settings,nav=[['today','Vandaag'],['scout','Autokansen'],['inbox','Gesprekken'],['deals','Dealdesk'],['settings','Inkoopprofiel'],['health','Agent & controle'],['billing','Abonnement']];
  return `<div class="shell"><aside class="sidebar"><div class="logo"><div class="brandmark">B</div><div class="brandtitle">BiedBot<small>EDGE · INKOOPDESK</small></div></div><div class="section-label">Je werkruimte</div><nav class="nav" aria-label="Hoofdnavigatie">${nav.map(([id,label])=>`<button data-page="${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}>${icon(id)}${label}${id==='deals'&&state.totals.hot?`<span class="count">${state.totals.hot}</span>`:''}</button>`).join('')}</nav><div class="side-bottom"><div class="local-box"><span class="dot"></span><strong>Lokaal op deze computer</strong><br>Geen proxy. Geen browser-VPS.<br>Gesprekken en sessies blijven hier.</div><div class="dealer"><div class="avatar">${esc(s.company.slice(0,2).toUpperCase())}</div><div><strong>${esc(s.company)}</strong><small>Lokale pilotomgeving</small></div></div></div></aside><main class="main"><header class="topbar"><span>Werkruimte &nbsp; / &nbsp; ${esc(nav.find(x=>x[0]===page)?.[1]||'Welkom')}</span><div class="topright"><span class="desktop-note">${esc(new Date().toLocaleDateString('nl-NL',{day:'numeric',month:'long',year:'numeric'}))}</span><span class="badge demo">DEMO · FICTIEVE DATA</span>${button('Pauzeer alles','stop','small danger')}</div></header>${content}<footer class="footer"><span>BiedBot Edge ${esc(state.version)} · lokale demonstratie · geen berichten naar echte verkopers</span><button class="textlink" data-action="health">Vrijgave & teststatus</button></footer></main></div>`;
}
function welcome(){return `<div class="onboarding"><div class="eyebrow">WELKOM BIJ JE DIGITALE INKOOPDESK</div><h1>Jij de auto's.<br>BiedBot het voorwerk.</h1><p class="sub">Stel je bedrijf één keer in en bekijk hoe de agent zelf selecteert, gesprekken voert en kansen overdraagt. De demonstratie gebruikt uitsluitend fictieve auto's en verkopers.</p><div class="stepper"><span class="active"></span><span></span><span></span></div><div class="card"><div class="card-head"><h2>Je autobedrijf</h2><span class="badge">Stap 1 · lokaal</span></div><div class="card-body"><form id="onboarding"><div class="form-grid"><label class="field wide">Bedrijfsnaam<input name="company" value="${esc(state.settings.company)}" required maxlength="100" autocomplete="organization"></label><label class="field">Afzender onder berichten<input name="signoff" value="${esc(state.settings.signoff)}" required maxlength="100"></label><label class="field">Vestigingsplaats<input name="town" value="${esc(state.settings.town)}" maxlength="100" placeholder="Bijvoorbeeld Delft"></label><label class="check-row wide"><input type="checkbox" name="understand" required> Ik begrijp dat dit een demo is, geen geactiveerde Marktplaats-koppeling.</label></div><div class="form-actions"><button class="button primary" type="submit">Open mijn inkoopdesk →</button></div><p class="helper">Geen betaalgegevens nodig. Er wordt niets automatisch afgeschreven.</p></form></div></div></div>`;}
function today(){
  const s=state.settings,active=state.conversations.filter(x=>!['HOT_LEAD','DECLINED','SUPPRESSED','PURCHASED','LOST','REVIEW'].includes(x.state.phase)).length;
  const top=state.candidates.filter(c=>c.eligible).slice(0,5);
  return heading('DAGOVERZICHT','Je volgende auto begint hier.','Alleen de kansen die bij jouw inkoopprofiel passen.',button(s.autopilot?'Autopilot pauzeren':'Start de demo','toggle',s.autopilot?'':'primary'))+
    `${state.stopReason?`<div class="banner"><div><strong>De agent is gepauzeerd</strong>${esc(state.stopReason)}</div></div>`:''}<div class="stats">${[
      ['Nieuwe contacten',`${state.usage.openings} <span>/ ${s.dailyCap}</span>`,'Interne cap · dag én laatste 24 uur'],
      ['Actieve gesprekken',number(active),'Zelfstandig binnen prijsplafond'],['Hete leads',number(state.totals.hot),'Prijs afgesproken · nog geen aankoop'],['Gereserveerd budget',money(state.committedBudget),`Van ${money(s.budget)} · demo bedragen`]
    ].map(([a,b,c])=>`<div class="stat"><div class="stat-label">${a}<span>↗</span></div><div class="stat-value">${b}</div><div class="stat-note">${c}</div></div>`).join('')}</div>
    <div class="grid"><section class="card autopilot"><div class="card-body"><div class="auto-top"><div><span class="pulse"></span><span class="auto-title">Je digitale inkoper</span></div><span class="badge">${s.autopilot?'DEMO ACTIEF':'KLAAR VOOR START'}</span></div><h2>${s.autopilot?'Hij doet het gesprek. Jij houdt het overzicht.':'Eén keer starten. Daarna kijkt BiedBot vooruit.'}</h2><p class="sub">Scouten, selecteren en onderhandelen. Zonder dat je elk bericht hoeft goed te keuren.</p><div class="flow"><span class="active">1 · Scout</span><b>›</b><span class="${state.usage.openings?'active':''}">2 · Selecteer</span><b>›</b><span class="${state.totals.sent?'active':''}">3 · Onderhandel</span><b>›</b><span class="${state.totals.hot?'active':''}">4 · Overdracht</span></div><div class="progress"><i id="quota-progress"></i></div><div class="auto-footer"><span>${state.usage.openings} van ${s.dailyCap} nieuwe contacten gereserveerd</span><span>${state.usage.total} / ${s.totalMessageCap} berichten totaal</span></div></div></section>
    <section class="card"><div class="card-head"><h2>Activiteit</h2><small>Werkelijke demo-events</small></div><div class="card-body">${activity(4)}</div></section></div>
    <div class="grid lower"><section class="card"><div class="card-head"><div><h2>Bovenaan je inkooplijst</h2><small>${state.totals.eligible} passende auto's · score is een rangschikking, geen kanspercentage</small></div>${button('Alle kansen →','scout','small')}</div>${top.map((c,i)=>`<div class="queue-row"><div class="queue-no">${String(i+1).padStart(2,'0')}</div><div class="queue-info"><strong>${esc(c.brand+' '+c.model)}</strong><small>${c.year} · ${number(c.mileage)} km · ${c.distanceKm} km afstand</small></div><span class="score">${c.score} / 100</span><div class="queue-price">${money(c.ask)}<small>fictieve vraagprijs</small></div></div>`).join('')}</section>
    <section class="card"><div class="card-head"><h2>Jouw vangnetten</h2><span class="badge green">In de code</span></div><div class="card-body"><div class="list-status"><span>Nieuwe contacten per account</span><strong>Maximaal 20</strong></div><div class="list-status"><span>Onderhandelrondes</span><strong>2 peilingen · 3 concessies</strong></div><div class="list-status"><span>Onzekere verzendstatus</span><strong>Geen herhaling</strong></div><div class="list-status"><span>Na akkoord of stopverzoek</span><strong>Bot stopt</strong></div><p class="helper">Een interne cap is geen door Marktplaats bevestigd veilig quotum. Livegebruik is nog niet vrijgegeven.</p></div></section></div>`;
}
function activity(n=20){return state.activity.slice(0,n).map(x=>`<div class="activity-item"><div class="activity-icon">${x.kind==='HOT_LEAD'?'✓':'·'}</div><div><strong>${esc(eventNames[x.kind]||x.kind)}</strong><small>${esc(x.detail)}</small></div><time class="activity-time">${clock(x.created)}</time></div>`).join('')||'<div class="empty">Start de demo om de agent in actie te zien.</div>';}
function scout(){
  const rows=state.candidates.filter(c=>(showAll||c.eligible)&&(`${c.brand} ${c.model}`.toLowerCase().includes(search.toLowerCase())));
  return heading('SCOUT & SELECTIE','De juiste twintig. Niet de eerste twintig.','BiedBot beoordeelt eerst je aanbod. Nieuwe contacten worden automatisch toegewezen.')+`<div class="filters"><input id="search" aria-label="Zoek merk of model" placeholder="Zoek merk of model…" value="${esc(search)}"><label class="check-row"><input type="checkbox" id="show-all" ${showAll?'checked':''}> Ook afgewezen kandidaten</label><span class="badge demo">Alle ${state.candidates.length} auto's zijn fictief</span></div><div class="card table-wrap"><table><thead><tr><th>Auto</th><th>Profiel</th><th>Score</th><th>Vraagprijs</th><th>Status / reden</th></tr></thead><tbody>${rows.map(c=>{const conv=state.conversations.find(x=>x.id===c.id);return `<tr><td><strong>${esc(c.brand+' '+c.model)}</strong><small>${esc(c.town)} · demonstratie</small></td><td>${c.year}<small>${number(c.mileage)} km · ${c.distanceKm} km afstand</small></td><td><span class="score">${c.score}/100</span></td><td>${money(c.ask)}<small>Geen actuele taxatie</small></td><td>${conv?badgePhase(conv.state.phase):c.eligible?'<span class="badge">In selectie</span>':`<span class="badge red">Niet passend</span><small>${esc(c.reasons.join(' · '))}</small>`}</td></tr>`;}).join('')}</tbody></table>${!rows.length?'<div class="empty">Geen kandidaten met deze filters.</div>':''}</div>`;
}
function inbox(){
  const conversations=state.conversations;
  if(!selected||!conversations.find(c=>c.id===selected))selected=conversations[0]?.id;
  const c=conversations.find(x=>x.id===selected);
  return heading('GESPREKSINTELLIGENTIE','Alle gesprekken. Eén overzicht.','Meekijken mag. Goedkeuren per bericht hoeft niet. Onzekerheden worden apart gezet.')+
    (!conversations.length?`<div class="card empty"><h3>De eerste gesprekken staan hier straks.</h3><p>Start de demo. BiedBot kiest zelf auto's en start de gesprekken.</p>${button('Start de demo','toggle','primary')}</div>`:`<div class="chat-layout"><div class="conversation-list">${conversations.map(c=>`<button class="conversation-item ${c.id===selected?'selected':''}" data-conversation="${esc(c.id)}"><strong>${esc(c.candidate.brand+' '+c.candidate.model)}</strong><small>${money(c.candidate.ask)} · fictieve verkoper</small><small>${badgePhase(c.state.phase)}</small></button>`).join('')}</div><section class="card chat"><div class="card-head"><div><h2>${esc(c.candidate.brand+' '+c.candidate.model)}</h2><small>Fictief gesprek · volledig automatische demonstratie</small></div>${badgePhase(c.state.phase)}</div><div class="chat-money"><div><span>Openingsanker</span><strong>${money(c.state.anchor)}</strong></div><div><span>Laatste eigen bod</span><strong>${money(c.state.lastOffer)}</strong></div><div><span>Hard plafond</span><strong>${money(c.state.ceiling)}</strong></div></div><div class="chat-body">${c.messages.map(m=>`<div class="bubble ${m.role}"><div class="bubble-meta">${m.role==='assistant'?'BIEDBOT · DEMOBERICHT':'FICTIEVE VERKOPER'} · ${clock(m.created)}</div>${esc(m.text)}</div>`).join('')||'<div class="empty">Eerste bericht is ingepland.</div>'}</div><div class="chat-footer">${['HOT_LEAD','REVIEW','DECLINED','SUPPRESSED','PURCHASED','LOST'].includes(c.state.phase)?'Gesprek gepauzeerd of afgesloten. De agent reageert hier niet verder.':`Autopilot voert het gesprek. ${c.state.peilingen}/2 peilingen · ${c.state.concessies}/3 concessies.`}<div class="buttons lower">${button('Overnemen / pauzeren','takeover','small',`data-id="${esc(c.id)}"`)}${button('Test een verkoperreactie','simulate','small',`data-id="${esc(c.id)}"`)}</div></div></section></div>`);
}
function deals(){const list=state.conversations.filter(c=>['HOT_LEAD','REVIEW','PURCHASED','LOST'].includes(c.state.phase));return heading('DEALDESK','Hier neem jij het over.','Een afgesproken prijs is nog geen gekochte auto. Controleer de auto en bevestig zelf de afspraak.')+
  `<div class="dealgrid">${list.map(c=>`<section class="card dealcard">${badgePhase(c.state.phase)}<h3>${esc(c.candidate.brand+' '+c.candidate.model)}</h3><p class="sub">${c.candidate.year} · ${number(c.candidate.mileage)} km · ${esc(c.candidate.town)}</p><div class="dealprice">${money(c.state.agreedPrice)}<small>Prijs voor bezichtiging, onder voorbehoud</small></div><div class="list-status"><span>Vraagprijs</span><strong>${money(c.candidate.ask)}</strong></div><div class="list-status"><span>Onderhoud</span><strong>Verkopersverklaring</strong></div><p class="helper">Geen fysieke inspectie uitgevoerd. Marge en gegevens zijn niet onafhankelijk geverifieerd.</p><div class="buttons">${button('Bekijk gesprek','view-conversation','small',`data-id="${esc(c.id)}"`)}${c.state.phase==='HOT_LEAD'?button('Gekocht','purchased','small primary',`data-id="${esc(c.id)}"`):''}${c.state.phase!=='PURCHASED'?button('Niet gekocht','lost','small',`data-id="${esc(c.id)}"`):''}</div></section>`).join('')||'<section class="card empty"><h3>Nog geen overdrachten.</h3><p>De demo onderhandelt door tot een prijs binnen het plafond is afgesproken, de verkoper afhaakt of controle nodig is.</p></section>'}</div>`;}
function settings(){const s=state.settings;const field=(title,key,type='number',extra='')=>`<label class="field">${title}<input name="${key}" type="${type}" value="${esc(s[key])}" ${extra}></label>`;return heading('INKOOPPROFIEL','Een keer goed instellen.','BiedBot houdt zich aan deze grenzen. De demo gebruikt dezelfde beslisregels.')+`<div class="grid"><section class="card"><div class="card-head"><h2>Je bedrijf & inkoopgrenzen</h2></div><div class="card-body"><form id="settings"><div class="form-grid">${field('Bedrijfsnaam','company','text','required maxlength="100"')}${field('Afzender','signoff','text','required maxlength="100"')}${field('Vestigingsplaats','town','text','maxlength="100"')}<label class="field">Merken (komma gescheiden)<input name="brands" value="${esc(s.brands.join(', '))}"></label>${field('Minimale vraagprijs (€)','minPrice','number','min="1000" max="200000" step="50"')}${field('Maximale vraagprijs (€)','maxPrice','number','min="1000" max="200000" step="50"')}${field('Bouwjaar vanaf','minYear','number','min="1980" max="2027"')}${field('Maximale kilometerstand','maxMileage','number','min="1000" max="999999"')}${field('Maximale afstand (km)','radiusKm','number','min="1" max="1000"')}${field('Openingskorting (%)','discountPct','number','min="8" max="60"')}${field('Nieuwe contacten per dag (max. 20)','dailyCap','number','min="1" max="20"')}${field('Alle uitgaande berichten (max. 80)','totalMessageCap','number','min="1" max="80"')}${field('Beschikbaar inkoopbudget (€)','budget','number','min="1000" max="10000000"')}${field('Doelmarge voor kostenraming (€)','minMargin','number','min="0" max="100000"')}${field('Extra risicoreserve (€)','riskReserve','number','min="0" max="100000"')}${field('Bewaartermijn als releasebeleid (dagen)','retentionDays','number','min="7" max="365"')}<label class="check-row wide"><input type="checkbox" name="requireMarginEvidence" ${s.requireMarginEvidence?'checked':''}> Alleen selecteren met ingevulde verkoopraming en kosten</label></div><div class="form-actions"><button class="button primary" type="submit">Inkoopprofiel opslaan</button></div></form></div></section><div><section class="card"><div class="card-head"><h2>Jouw gespreksstrategie</h2></div><div class="card-body"><div class="release-list">1. Opening zonder prijs<br>2. Brug en openingsanker<br>3. Hoogstens twee peilingen<br>4. Hoogstens drie aflopende concessies<br>5. Binnen het plafond: prijs bevestigen<br>6. Stoppen en overdragen</div><p class="helper">Nieuwe fasemachine uit jouw gespreksbestand. Geen verzonnen marktonderzoek, eigen afspraakdatum of ongecontroleerde AI-bedragen.</p></div></section><section class="card lower"><div class="card-body"><h3>Bewaartermijn</h3><p class="sub">De termijn is opgenomen als releasebeleid. Automatische productie-opschoning is nog niet vrijgegeven. De demo kan volledig worden herstart.</p></div></section></div></div>`;}
function health(){const age=state.worker?Date.now()-state.worker.heartbeat:Infinity;const checks=[['Lokale database','Actief · SQLite'],['Worker-heartbeat',age<10000?'Recent ontvangen':'Geen recente heartbeat'],['Omgeving','Geïsoleerde demo'],['Marktplaats-toegang','Niet live vrijgegeven'],['Windows-installatietest','Nog op echte Windows-pc uitvoeren'],['AI in deze demo','Offline regels · geen API-kosten'],['Betaalprovider','Niet gekoppeld'],['Softwarehandtekening','Deze pilot is niet ondertekend']];return heading('BETROUWBAARHEID','Duidelijk wat draait. En wat nog niet.','Geen groene status zonder controle. Deze build benadert geen echte Marktplaats-verkopers.')+`<div class="grid"><section class="card"><div class="card-head"><h2>Agent & vrijgave</h2><span class="badge demo">PILOT</span></div><div class="card-body">${checks.map(([a,b])=>`<div class="list-status"><span>${a}</span><strong>${b}</strong></div>`).join('')}<p class="helper">Een captcha, gewijzigde pagina of onzekere verzendstatus mag nooit stilzwijgend tot herhaald versturen leiden. De browseradapter heeft lokale contracttests. De volledige browsernavigatietest is in deze bouwomgeving geblokkeerd en is geen geslaagde Marktplaats-praktijktest.</p><div class="buttons lower">${button('Open apart Marktplaats-profiel','browser','small')}${button('Supportrapport','support','small')}</div></div></section><section class="card"><div class="card-head"><h2>Gegevens & noodstop</h2></div><div class="card-body"><p class="sub">Export blijft op jouw computer. Het supportrapport bevat geen volledige gespreksteksten of browsercookies.</p><div class="buttons lower">${button('JSON exporteren','export','small')}${button('Versleutelde export','backup','small')}</div><div class="buttons lower">${button('Pauzeer alles','stop','danger')}${button('Demo herstarten','reset','small')}${button('Agent afsluiten','shutdown','small')}</div><p class="helper">Pauzeren stopt nieuwe acties. Een bericht dat al in uitvoering is, kan nog worden afgerond. Afsluiten stopt de lokale agent; de computer moet aanstaan om te werken.</p></div></section></div><section class="card lower"><div class="card-head"><h2>Audittrail</h2><small>Geen verzonnen live-activiteit</small></div><div class="card-body">${activity(20)}</div></section>`;}
function billing(){const s=state.settings;return heading('DEMO → PILOT → ABONNEMENT','Eerst ervaren. Daarna pas activeren.','Commercieel voorstel voor jouw product. Niet gepubliceerd en niet automatisch afgeschreven.')+`<div class="grid"><section class="card"><div class="card-head"><h2>Dealer-abonnement</h2><span class="badge demo">Prijsvoorstel</span></div><div class="card-body"><div class="price-big">${money(s.pricingMonthly)}<small> / maand, exclusief btw</small></div><div class="price-line">Eenmalige inrichting: <strong>${money(s.pricingSetup)} excl. btw</strong></div><div class="price-line">Voorstel: ${s.trialDays} dagen live pilot na technische en platformvrijgave</div><div class="price-line">Gratis offline demo zonder betaalgegevens</div><div class="price-line">Lokale agent, inkoopprofiel, onderhandelingen en dealoverdracht</div><div class="price-line">Onboarding op afstand mogelijk via download en eigen login</div><div class="buttons lower"><button class="button primary" disabled>Checkout nog niet gekoppeld</button></div><p class="helper">De broncode bevat betaal- en licentiecomponenten. Er is nog geen gepubliceerde checkout, incassomachtiging of actief abonnement. Kosten van AI-gebruik en support moeten vóór verkoop in het aanbod worden vastgelegd.</p></div></section><section class="card"><div class="card-head"><h2>Zelf installeren, zonder bezoek</h2></div><div class="card-body"><div class="release-list"><strong>1. Download de app</strong><br>Persoonlijke installatie op de computer van de dealer.<br><br><strong>2. Stel het inkoopprofiel in</strong><br>Bedrijfsnaam, merken, grenzen en beschikbaar budget.<br><br><strong>3. Ervaar de demo</strong><br>Automatische gesprekken met fictieve verkopers.<br><br><strong>4. Vrijgave vóór livegebruik</strong><br>Windows-test, platformtoegang, echte gesprekstest en betalingsinstellingen.</div></div></section></div>`;}
function render(){if(!state)return;const pages={today,scout,inbox,deals,settings,health,billing};$('#app').innerHTML=layout(!state.settings.onboardingDone?welcome():(pages[page]||today)());
  const bar=$('#quota-progress');if(bar)bar.style.width=`${Math.min(100,state.usage.openings/state.settings.dailyCap*100)}%`;
}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
document.addEventListener('click',async e=>{
  const nav=e.target.closest('[data-page]');if(nav){page=nav.dataset.page;render();return;}
  const conv=e.target.closest('[data-conversation]');if(conv){selected=conv.dataset.conversation;render();return;}
  const el=e.target.closest('[data-action]');if(!el||busy)return;busy=true;
  try{const a=el.dataset.action,id=el.dataset.id;
    if(['health','scout'].includes(a)){page=a;render();return;}
    if(a==='toggle'){await post('autopilot',{enabled:!state.settings.autopilot});toast(state.settings.autopilot?'Autopilot gepauzeerd.':'Demonstratie gestart. Er worden geen echte verkopers benaderd.');}
    if(a==='stop'){await post('autopilot',{enabled:false});toast('Nieuwe acties gepauzeerd.');}
    if(a==='reset'){if(!confirm('Alle fictieve gesprekken en demoresultaten verwijderen en opnieuw beginnen?'))return;await post('demo/reset',{confirm:'DEMO HERSTARTEN'});toast('Demo herstart.');}
    if(a==='takeover'){await post('deal/status',{id,phase:'REVIEW'});toast('Gesprek overgenomen. De bot reageert hier niet meer.');}
    if(a==='purchased'||a==='lost'){await post('deal/status',{id,phase:a==='purchased'?'PURCHASED':'LOST'});toast('Demo-dealstatus bijgewerkt.');}
    if(a==='view-conversation'){page='inbox';selected=id;render();return;}
    if(a==='simulate'){const text=prompt('Fictieve verkoperreactie. Deze test verstuurt niets naar Marktplaats.','Is goed, akkoord.');if(text)await post('demo/reply',{id,text});}
    if(a==='export')download('BiedBot-demo-export.json',JSON.stringify(await api('export'),null,2));
    if(a==='support')download('BiedBot-support.json',JSON.stringify(await api('support'),null,2));
    if(a==='backup'){const password=prompt('Wachtwoord voor versleutelde export (minimaal 12 tekens). Bewaar het zelf.');if(!password)return;download('BiedBot-versleutelde-export.json',JSON.stringify(await post('backup',{password})));toast('Versleutelde export opgeslagen.');}
    if(a==='browser'){const r=await post('open-marktplaats');toast(r.note);}
    if(a==='shutdown'){if(!confirm('De lokale agent volledig afsluiten?'))return;await post('shutdown');$('#app').innerHTML='<div class="loading"><h1>Agent afgesloten.</h1><p>Je gegevens blijven bewaard. Open BiedBot opnieuw via de snelkoppeling.</p></div>';return;}
    await refresh(true);
  }catch(e){toast(e.message,true);}finally{busy=false;}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;const pos=e.target.selectionStart;render();$('#search')?.focus();$('#search')?.setSelectionRange(pos,pos);}});
document.addEventListener('change',e=>{if(e.target.id==='show-all'){showAll=e.target.checked;render();}});
document.addEventListener('submit',async e=>{
  if(!['onboarding','settings'].includes(e.target.id))return;e.preventDefault();const f=new FormData(e.target);const data={};
  try{if(e.target.id==='onboarding'){Object.assign(data,{company:f.get('company'),signoff:f.get('signoff'),town:f.get('town'),onboardingDone:true});}
    else{for(const [k,v]of f){if(k==='brands')data[k]=String(v).split(',').map(x=>x.trim()).filter(Boolean);else if(['company','signoff','town'].includes(k))data[k]=v;else if(k!=='requireMarginEvidence')data[k]=Number(v);}data.requireMarginEvidence=f.has('requireMarginEvidence');}
    await post('settings',data);toast('Inkoopprofiel opgeslagen.');if(e.target.id==='onboarding')page='today';await refresh(true);
  }catch(e){toast(e.message,true);}
});
async function boot(){try{const token=location.hash.slice(1);if(token){const r=await post('session',{token});csrf=r.csrf;history.replaceState(null,'',location.pathname);}await refresh(true);if(!state)throw new Error('Open de app opnieuw via de snelkoppeling.');setInterval(()=>refresh(),1800);}catch(e){$('#app').innerHTML=`<div class="loading"><div class="brandmark">B</div><h1>Open BiedBot via de snelkoppeling.</h1><p>${esc(e.message)}</p><p>Een los HTML-bestand is niet de lokale agent.</p></div>`;}}
boot();
