import {readFileSync,writeFileSync,existsSync} from 'node:fs';import {spawnSync} from 'node:child_process';
const tap=readFileSync('reports/unit-tests.tap','utf8');const val=k=>Number(tap.match(new RegExp('^# '+k+' (\\d+)$','m'))?.[1]||0);
const dom=JSON.parse(readFileSync('reports/browser-dom-tests.json'));const browser=JSON.parse(readFileSync('reports/browser-tests.json'));
const browserVersion=spawnSync('/usr/bin/chromium',['--version'],{encoding:'utf8'}).stdout?.trim()||'Zie browserlog';
const report={build:'0.1.0-pilot.1',createdAt:new Date().toISOString(),release:'DEMO_TESTED_NOT_LIVE_RELEASED',environment:{platform:process.platform,node:process.version,browser:browserVersion},unit:{tests:val('tests'),passed:val('pass'),failed:val('fail'),skipped:val('skipped'),report:'reports/unit-tests.tap'},pricePropertyCases:10000,dom:{passed:dom.passed,failed:dom.failed,scope:dom.scope},browserNavigation:{status:'ENVIRONMENT_BLOCKED',passed:browser.passed,failed:browser.failed,error:'net::ERR_BLOCKED_BY_ADMINISTRATOR',scope:browser.scope},windowsInstaller:'NOT_EXECUTED',realMarktplaats:'NOT_EXECUTED',liveAI:'NOT_EXECUTED_MOCKS_ONLY',mollie:'NOT_EXECUTED_MOCKS_ONLY',remoteCodexTask:'NOT_STARTED',remoteCI:'NOT_RUN',notes:['No administrator browser restriction was changed or bypassed.','DOM tests use in-memory fetch fixtures, not real platform communication.','The test counts are not a code coverage percentage or a bug-free guarantee.']};
writeFileSync('reports/test-summary.json',JSON.stringify(report,null,2));
const text=`# Testrapport BiedBot Edge\n\nBuild ${report.build}. Uitgevoerd ${report.createdAt}.\n\n## Hoofdresultaat\n\n**${report.unit.passed}/${report.unit.tests} Node-tests geslaagd, ${report.unit.failed} gefaald. ${dom.passed} Chromium-DOMtests geslaagd. Volledige browsernavigatie geblokkeerd; Windows en echte Marktplaats niet getest.**\n\nDe tests draaien op ${process.platform}, ${process.version}, ${browserVersion}. De hele lokale HTTP-app start bovendien een echte workerthread die autonoom een demo-overdracht opslaat. Geen berichtgoedkeuring of kunstmatige front-endteller.\n\n## Wat is getest\n\nPrijsbanden, ankerafronding, 10.000 berekende prijsgevallen, concessies, laatste bod bij akkoord, prijsloze opening, negaties, uitnodigingen, onderhoudstekst, andere bieders, telefoon-/km-/jaargetallen, onbekende AI-uitvoer, harde caps, budget, deduplicatie, vier gelijktijdige reserverende workers, 24 uur en lokale dag, ontvangstbewijs, onzeker verzendresultaat, herstart, opt-out, laatste verkoperbericht, menselijke overname, HTTP-authenticatie, Host/Origin/CSRF, inputvalidatie, encrypted export, AI-budget, providerfouten, licentiehandtekening, verlopen/cross-device licentie, Mollie-idempotency en betaling-/mandaatcontrole.\n\n## Browser: onderscheid is essentieel\n\n1. De volledige test tegen een eigen lokale fixturewebsite werd geprobeerd. Chromium blokkeerde de eerste navigatie met net::ERR_BLOCKED_BY_ADMINISTRATOR. Dat is een geblokkeerde test, geen geslaagde browserintegratie. De beheerdersbeperking is niet aangepast. Zie reports/browser-tests.json.\n2. De eigen interface is daarna via het DOM van een lege Chromium-pagina getest, zonder navigatie of browsernetwerk. Fetch-responsen zijn in deze UI-test gemockt. Onboarding, API-verzoekvelden, navigatie, inbox, noodstop, runtimefouten en mobiele breedte zijn gecontroleerd. Zie reports/browser-dom-tests.json.\n3. De lokale HTTP-backend en echte applicatieworker zijn los daarvan wél echt uitgevoerd en getest; daarvoor is geen browsermock gebruikt.\n\n## Niet bewezen\n\nWindows-installatie/PowerShell-uitvoering, actuele ingelogde Marktplaats-DOM, daadwerkelijke ontvangst bij een verkoper, accountveiligheid, live Claude-taalbegrip, echte Mollie-webhooks/incasso, externe security review, update/signing en langdurig productiebedrijf. Er is geen code-coveragepercentage gemeten en geen garantie dat er geen bugs meer zijn.\n\n## Resultaatbestanden\n\nreports/unit-tests.tap is de definitieve Node-run; reports/test-summary.json is de machineleesbare samenvatting; reports/browser-dom-tests.json en reports/browser-tests.json houden UI en navigatie gescheiden. Historische eerste runs staan in reports/history en kunnen bewust oude, later herstelde failures bevatten. Een klaarstaand CI-workflowbestand is geen uitgevoerde CI-run.\n`;
writeFileSync('docs/TESTRESULTATEN.md',text);
console.log(JSON.stringify(report,null,2));
